/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as HrmsRouteImport } from './routes/hrms'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as MrpRouteImport } from './routes/mrp'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as WarehouseRouteImport } from './routes/warehouse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsRoute = HrmsRouteImport.update({
  id: '/hrms',
  path: '/hrms',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const MrpRoute = MrpRouteImport.update({
  id: '/mrp',
  path: '/mrp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/attendance': typeof AttendanceRoute
  '/crm': typeof CrmRoute
  '/customers': typeof CustomersRoute
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/hrms': typeof HrmsRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/leads': typeof LeadsRoute
  '/manufacturing': typeof ManufacturingRoute
  '/mrp': typeof MrpRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/production': typeof ProductionRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/purchase': typeof PurchaseRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/warehouse': typeof WarehouseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/attendance': typeof AttendanceRoute
  '/crm': typeof CrmRoute
  '/customers': typeof CustomersRoute
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/hrms': typeof HrmsRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/leads': typeof LeadsRoute
  '/manufacturing': typeof ManufacturingRoute
  '/mrp': typeof MrpRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/production': typeof ProductionRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/purchase': typeof PurchaseRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/warehouse': typeof WarehouseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/attendance': typeof AttendanceRoute
  '/crm': typeof CrmRoute
  '/customers': typeof CustomersRoute
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/hrms': typeof HrmsRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/leads': typeof LeadsRoute
  '/manufacturing': typeof ManufacturingRoute
  '/mrp': typeof MrpRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/production': typeof ProductionRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/purchase': typeof PurchaseRoute
  '/quality': typeof QualityRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/tasks': typeof TasksRoute
  '/warehouse': typeof WarehouseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/analytics'
    | '/approvals'
    | '/attendance'
    | '/crm'
    | '/customers'
    | '/employees'
    | '/finance'
    | '/hrms'
    | '/integrations'
    | '/inventory'
    | '/leads'
    | '/manufacturing'
    | '/mrp'
    | '/notifications'
    | '/payroll'
    | '/production'
    | '/profile'
    | '/projects'
    | '/purchase'
    | '/quality'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/tasks'
    | '/warehouse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/analytics'
    | '/approvals'
    | '/attendance'
    | '/crm'
    | '/customers'
    | '/employees'
    | '/finance'
    | '/hrms'
    | '/integrations'
    | '/inventory'
    | '/leads'
    | '/manufacturing'
    | '/mrp'
    | '/notifications'
    | '/payroll'
    | '/production'
    | '/profile'
    | '/projects'
    | '/purchase'
    | '/quality'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/tasks'
    | '/warehouse'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/analytics'
    | '/approvals'
    | '/attendance'
    | '/crm'
    | '/customers'
    | '/employees'
    | '/finance'
    | '/hrms'
    | '/integrations'
    | '/inventory'
    | '/leads'
    | '/manufacturing'
    | '/mrp'
    | '/notifications'
    | '/payroll'
    | '/production'
    | '/profile'
    | '/projects'
    | '/purchase'
    | '/quality'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/tasks'
    | '/warehouse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AttendanceRoute: typeof AttendanceRoute
  CrmRoute: typeof CrmRoute
  CustomersRoute: typeof CustomersRoute
  EmployeesRoute: typeof EmployeesRoute
  FinanceRoute: typeof FinanceRoute
  HrmsRoute: typeof HrmsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InventoryRoute: typeof InventoryRoute
  LeadsRoute: typeof LeadsRoute
  ManufacturingRoute: typeof ManufacturingRoute
  MrpRoute: typeof MrpRoute
  NotificationsRoute: typeof NotificationsRoute
  PayrollRoute: typeof PayrollRoute
  ProductionRoute: typeof ProductionRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  PurchaseRoute: typeof PurchaseRoute
  QualityRoute: typeof QualityRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRoute
  TasksRoute: typeof TasksRoute
  WarehouseRoute: typeof WarehouseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms': {
      id: '/hrms'
      path: '/hrms'
      fullPath: '/hrms'
      preLoaderRoute: typeof HrmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mrp': {
      id: '/mrp'
      path: '/mrp'
      fullPath: '/mrp'
      preLoaderRoute: typeof MrpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiAssistantRoute: AiAssistantRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AttendanceRoute: AttendanceRoute,
  CrmRoute: CrmRoute,
  CustomersRoute: CustomersRoute,
  EmployeesRoute: EmployeesRoute,
  FinanceRoute: FinanceRoute,
  HrmsRoute: HrmsRoute,
  IntegrationsRoute: IntegrationsRoute,
  InventoryRoute: InventoryRoute,
  LeadsRoute: LeadsRoute,
  ManufacturingRoute: ManufacturingRoute,
  MrpRoute: MrpRoute,
  NotificationsRoute: NotificationsRoute,
  PayrollRoute: PayrollRoute,
  ProductionRoute: ProductionRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  PurchaseRoute: PurchaseRoute,
  QualityRoute: QualityRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRoute,
  TasksRoute: TasksRoute,
  WarehouseRoute: WarehouseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
